#!/bin/bash
#SBATCH --ntasks=6
#SBATCH --mem=14G
#SBATCH --gres=gpu:1
#SBATCH -t 2-00:00:00
#SBATCH -o j_out.out
#SBATCH -e j_err.log

# This is the temporary dir for your job on the SSD
# It will be deleted once your job finishes so don't forget to copy your files!

MY_TMP_DIR=/slurmtmp/${SLURM_JOB_USER}.${SLURM_JOB_ID}

#cd /media/data/kderaad/

#. /media/data/kderaad/python36/bin/activate

#cd glassimaging

kak moet ik nog doen TODO

kak kak kak
