mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-0.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-1.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-10.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-100.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-101.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-102.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-103.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-104.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-105.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-106.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-107.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-108.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-109.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-11.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-110.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-111.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-112.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-113.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-114.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-115.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-116.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-117.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-118.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-119.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-12.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-120.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-121.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-122.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-123.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-124.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-125.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-126.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-127.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-128.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-129.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-13.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-130.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-14.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-15.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-16.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-17.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-18.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-19.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-2.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-20.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-21.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-22.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-23.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-24.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-25.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-26.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-27.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-28.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-29.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-3.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-30.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-31.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-32.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-33.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-34.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-35.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-36.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-37.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-38.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-39.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-4.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-40.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-41.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-42.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-43.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-44.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-45.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-46.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-47.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-48.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-49.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-5.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-50.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-51.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-52.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-53.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-54.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-55.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-56.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-57.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-58.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-59.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-6.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-60.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-61.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-62.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-63.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-64.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-65.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-66.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-67.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-68.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-69.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-7.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-70.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-71.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-72.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-73.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-74.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-75.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-76.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-77.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-78.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-79.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-8.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-80.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-81.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-82.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-83.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-84.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-85.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-86.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-87.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-88.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-89.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-9.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-90.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-91.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-92.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-93.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-94.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-95.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-96.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-97.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-98.nii
mkdir -p C:Users\s145576\Documents\GitHub\automaticSegmentationThesis\data\Lits_N4BC\volume-99.nii
